spring:
  application:
     name: backend
  resources:
     static-locations == classpath:static/,file:static/
  redis:
     database: 0 
     host: 127.0.0.1 
      #password:  
     port: 6379
     timeout: 20000
     pool: 
        #最大连接数
        max-active: 8
        #最大阻塞等待时间(负数表示没限制)
        max-wait: -1
        #最大空闲
        max-idle: 8
        #最小空闲
        min-idle: 0
server:
  port: 8105
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8100/eureka/